Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
  '''The first line Vagrant.configure("2") do |config| initializes the Vagrant configuration 
    and sets the version to "2". 
    This ensures compatibility with the Vagrant 2.x syntax.
    * config.hostmanager.enabled = true enables the Vagrant Hostmanager plugin, which 
    automatically manages the hosts /etc/hosts file to resolve hostnames of 
    the virtual machines.
    * config.hostmanager.manage_host = true indicates that Vagrant 
    should manage the host entries for the virtual machines defined in the Vagrantfile.
    '''
    ### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provision "shell", path: "mysql.sh"  

  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "geerlingguy/centos7"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provision "shell", path: "memcache.sh"  
  end
 ''' section defines a virtual machine called "db01". 
 It uses the "geerlingguy/centos7" box, which is a CentOS 7 image provided by the "geerlingguy" box provider. 
 The virtual machines hostname is set to "db01".

 The line db01.vm.network "private_network", ip: "192.168.56.15" creates a private network interface within the virtual machine and
 assigns the IP address "192.168.56.15" to it.
 
 The line db01.vm.provision "shell", path: "mysql.sh" specifies that a shell script called "mysql.sh" should be executed during the provisioning process of the "db01" virtual machine. 
 This script likely contains commands to install and configure MySQL.''' 
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "geerlingguy/centos7"
  rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
    rmq01.vm.provision "shell", path: "rabbitmq.sh"  
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "geerlingguy/centos7"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provision "shell", path: "tomcat.sh"  
    app01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
   end
   
  ''' app01.vm.network "private_network", ip: "192.168.56.12" assigns the IP address "192.168.56.12" 
  to the private network interface of the "app01" virtual machine.

  The line app01.vm.provision "shell", path: "tomcat.sh" specifies that a shell script called "tomcat.sh" should be executed 
  during the provisioning process of the "app01" virtual machine. 
  This script likely contains commands to install and configure Apache Tomcat.
  
  The nested block app01.vm.provider "virtualbox" do |vb| allows for provider-specific configuration. In this case, it configures the VirtualBox provider and sets the memory allocation for the "app01" virtual machine to "1024" MB.'''

   ### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/xenial64"
    web01.vm.hostname = "web01"
  web01.vm.network "private_network", ip: "192.168.56.11"
  web01.vm.provision "shell", path: "nginx.sh"  
end
  
end  #  the end statement concludes the Vagrant configuration block.


''' this Vagrantfile sets up multiple virtual machines with different purposes using CentOS 
and Ubuntu images. 
Each virtual machine is assigned a private IP address, 
and provisioning shell scripts are executed to install and configure the necessary software on each machine. 
The Vagrant Hostmanager plugin is enabled to manage the host entries for the virtual machines.'''